name: app_version_update
description: An easy and quick way to check if the local app is updated with the same version in their respective stores (Play Store / Apple Store ).
# author: KauÃª Tomaz Murakami<kauetmurakami@gmail.com>
version: 6.1.2
homepage: https://github.com/kauemurakami/app_version_update

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: 1.3.0
  package_info_plus: ^8.0.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
